### ISSUE TITLE
Fertig?

### ISSUE THREAD

**Issue by adrijanb** [Sachs-Media/sevdeskapi#1]
Hey,

Wir sind auf der Suche nach einer SDK für Sevdesk. Ist deine SDK fertig?

**Comment by eieste** [comment]
Hi,

Jain. Es funktioniert grundlegend.
Aber es zu erweitern ist nicht schwer...

Wir haben nur Funktionalitäten die wir selbst benötigten eingebaut

Gruß 

Stefan
