### ISSUE TITLE
Documentation not working

### ISSUE THREAD

**Issue by FelixWeichselgartner** [Sachs-Media/sevdeskapi#2]
Hey, came across your project.

I think your docArea link is not working properly.

Greetings

**Comment by eieste** [comment]
hey

thanks a lot for your hint.
docArea is currently another project of mine, which is still very unfinished.
Unfortunately the documentation and the project itself is not very far developed. I will try to improve this in the next months. If you want to use the project on a short-run, I can help you  

Kind Regards
